### Extract the blast features

**Combine the blast hit result log files from cluster and create combine dataframe of 8941896 rows.
Filter the dataframe for hits that have query converage of 100% and identity percentage of 80% or more.
combined the results for each unique sequence ID.
count_blast - total count of blast hits for the sequence
AvgIdBlast - Average of the Identity Percentage of those hits**

In [1]:
import pandas as pd

In [6]:
#Loading the log files from the blast search result output

import pandas as pd

blast_1 = pd.read_csv("uniprot_blast_results/uniprot_blast_query_1.log", sep='\t', header=None)
blast_1.columns = ["id", "subject_id", "identity_percentage", "alignment_length", "mismatches", "gap_opens", "query_start", "query_end", "subject_start", "subject_end", "expect_value", "bit_score", "query_coverage"]
blast_1

,id,subject_id,identity_percentage,alignment_length,mismatches,gap_opens,query_start,query_end,subject_start,subject_end,expect_value,bit_score,query_coverage
0,A0A068FVC1,ref|WP_096106374.1|,100.000,179,0,0,1,179,1,179,2.120000e-130,373.0,100
1,A0A068FVC1,ref|WP_268029297.1|,99.441,179,1,0,1,179,1,179,4.280000e-130,372.0,100
2,A0A068FVC1,gb|AXL04880.1|,99.441,179,1,0,1,179,1,179,9.850000e-130,371.0,100
3,A0A068FVC1,ref|WP_101613939.1|,99.441,179,1,0,1,179,1,179,1.560000e-129,371.0,100
4,A0A068FVC1,ref|WP_279451246.1|,97.765,179,4,0,1,179,1,179,4.460000e-126,362.0,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1500895,A0A1Z1NWL7,ref|WP_124252906.1|,74.185,399,103,0,1,399,1,399,0.000000e+00,618.0,100
1500896,A0A1Z1NWL7,ref|WP_171280179.1|,74.185,399,103,0,1,399,1,399,0.000000e+00,618.0,100
1500897,A0A1Z1NWL7,ref|WP_026455881.1|,74.687,399,101,0,1,399,1,399,0.000000e+00,618.0,100
1500898,A0A1Z1NWL7,ref|WP_202010714.1|,74.185,399,103,0,1,399,1,399,0.000000e+00,617.0,100
1500899,A0A1Z1NWL7,ref|WP_263675075.1|,74.185,399,103,0,1,399,1,399,0.000000e+00,617.0,100

In [7]:
blast_2 = pd.read_csv("uniprot_blast_results/uniprot_blast_query_2.log", sep='\t', header=None)
blast_2.columns = ["id", "subject_id", "identity_percentage", "alignment_length", "mismatches", "gap_opens", "query_start", "query_end", "subject_start", "subject_end", "expect_value", "bit_score", "query_coverage"]
blast_2

,id,subject_id,identity_percentage,alignment_length,mismatches,gap_opens,query_start,query_end,subject_start,subject_end,expect_value,bit_score,query_coverage
0,A0A1Z1NWN0,ref|WP_005316007.1|,100.000,286,0,0,1,286,1,286,0.0,598.0,100
1,A0A1Z1NWN0,ref|WP_042468795.1|,99.650,286,1,0,1,286,1,286,0.0,597.0,100
2,A0A1Z1NWN0,gb|ATU99391.1|,99.650,286,1,0,1,286,1,286,0.0,597.0,100
3,A0A1Z1NWN0,gb|ATP07704.1|,99.301,286,2,0,1,286,1,286,0.0,597.0,100
4,A0A1Z1NWN0,gb|KTA91954.1|,99.650,286,1,0,1,286,1,286,0.0,597.0,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1501113,A0A2S4U8G5,ref|WP_215270015.1|,83.417,398,66,0,1,398,1,398,0.0,668.0,100
1501114,A0A2S4U8G5,ref|WP_123173393.1|,83.586,396,65,0,1,396,1,396,0.0,668.0,99
1501115,A0A2S4U8G5,ref|WP_163148600.1|,85.052,388,58,0,1,388,1,388,0.0,668.0,97
1501116,A0A2S4U8G5,ref|WP_041208389.1|,84.171,398,62,1,1,397,1,398,0.0,668.0,99
1501117,A0A2S4U8G5,ref|WP_279699205.1|,82.915,398,68,0,1,398,1,398,0.0,668.0,100

In [8]:
blast_3 = pd.read_csv("uniprot_blast_results/uniprot_blast_query_3.log", sep='\t', header=None)
blast_3.columns = ["id", "subject_id", "identity_percentage", "alignment_length", "mismatches", "gap_opens", "query_start", "query_end", "subject_start", "subject_end", "expect_value", "bit_score", "query_coverage"]
blast_3

,id,subject_id,identity_percentage,alignment_length,mismatches,gap_opens,query_start,query_end,subject_start,subject_end,expect_value,bit_score,query_coverage
0,A0A2S4U8I7,ref|WP_041211114.1|,100.000,361,0,0,1,361,1,361,0.0,742.0,100
1,A0A2S4U8I7,ref|WP_161470222.1|,99.723,361,1,0,1,361,1,361,0.0,741.0,100
2,A0A2S4U8I7,ref|WP_151028362.1|,99.723,361,1,0,1,361,1,361,0.0,741.0,100
3,A0A2S4U8I7,ref|WP_201956246.1|,99.723,361,1,0,1,361,1,361,0.0,741.0,100
4,A0A2S4U8I7,ref|WP_201984591.1|,99.723,361,1,0,1,361,1,361,0.0,741.0,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1501767,A0A653KER4,ref|WP_257703576.1|,98.131,428,8,0,1,428,1,428,0.0,861.0,100
1501768,A0A653KER4,ref|WP_158110470.1|,97.664,428,10,0,1,428,1,428,0.0,861.0,100
1501769,A0A653KER4,ref|WP_236346980.1|,97.897,428,9,0,1,428,1,428,0.0,860.0,100
1501770,A0A653KER4,ref|WP_279700778.1|,97.664,428,10,0,1,428,1,428,0.0,860.0,100
1501771,A0A653KER4,ref|WP_201946959.1|,97.664,428,10,0,1,428,1,428,0.0,860.0,100

In [9]:
blast_4 = pd.read_csv("uniprot_blast_results/uniprot_blast_query_4.log", sep='\t', header=None)
blast_4.columns = ["id", "subject_id", "identity_percentage", "alignment_length", "mismatches", "gap_opens", "query_start", "query_end", "subject_start", "subject_end", "expect_value", "bit_score", "query_coverage"]
blast_4

,id,subject_id,identity_percentage,alignment_length,mismatches,gap_opens,query_start,query_end,subject_start,subject_end,expect_value,bit_score,query_coverage
0,A0A653KEU0,ref|WP_159165529.1|,100.000,763,0,0,1,763,1,763,0.0,1561.0,100
1,A0A653KEU0,ref|WP_265462611.1|,99.346,764,4,1,1,763,1,764,0.0,1550.0,100
2,A0A653KEU0,ref|WP_111589694.1|,99.215,764,5,1,1,763,1,764,0.0,1550.0,100
3,A0A653KEU0,gb|RAI98623.1|,99.215,764,5,1,1,763,12,775,0.0,1549.0,100
4,A0A653KEU0,ref|WP_131731593.1|,98.953,764,7,1,1,763,1,764,0.0,1546.0,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1501154,A0A7I6PXU6,ref|WP_026140882.1|,93.519,324,21,0,1,324,1,324,0.0,615.0,100
1501155,A0A7I6PXU6,ref|WP_185423543.1|,93.519,324,21,0,1,324,1,324,0.0,615.0,100
1501156,A0A7I6PXU6,ref|WP_130632223.1|,93.210,324,22,0,1,324,18,341,0.0,615.0,100
1501157,A0A7I6PXU6,ref|WP_240533573.1|,90.123,324,32,0,1,324,1,324,0.0,614.0,100
1501158,A0A7I6PXU6,ref|WP_265345642.1|,90.123,324,32,0,1,324,9,332,0.0,614.0,100

In [10]:
blast_5 = pd.read_csv("uniprot_blast_results/uniprot_blast_query_5.log", sep='\t', header=None)
blast_5.columns = ["id", "subject_id", "identity_percentage", "alignment_length", "mismatches", "gap_opens", "query_start", "query_end", "subject_start", "subject_end", "expect_value", "bit_score", "query_coverage"]
blast_5

,id,subject_id,identity_percentage,alignment_length,mismatches,gap_opens,query_start,query_end,subject_start,subject_end,expect_value,bit_score,query_coverage
0,A0A7I6PXX4,ref|WP_039038908.1|,100.000,424,0,0,1,424,1,424,0.000000e+00,884.0,100
1,A0A7I6PXX4,ref|WP_119197732.1|,99.764,424,1,0,1,424,1,424,0.000000e+00,884.0,100
2,A0A7I6PXX4,ref|WP_223915555.1|,99.764,424,1,0,1,424,1,424,0.000000e+00,882.0,100
3,A0A7I6PXX4,ref|WP_270793005.1|,99.764,424,1,0,1,424,1,424,0.000000e+00,882.0,100
4,A0A7I6PXX4,ref|WP_069784837.1|,99.764,424,1,0,1,424,1,424,0.000000e+00,882.0,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1501639,A0A8H9RDU4,ref|WP_165880411.1|,68.536,321,101,0,5,325,9,329,3.770000e-167,478.0,98
1501640,A0A8H9RDU4,ref|WP_033849302.1|,68.519,324,102,0,3,326,4,327,3.820000e-167,478.0,99
1501641,A0A8H9RDU4,ref|WP_150015819.1|,68.438,320,101,0,6,325,7,326,4.030000e-167,478.0,98
1501642,A0A8H9RDU4,gb|EFC1526849.1|,68.438,320,97,1,6,325,7,322,4.060000e-167,478.0,98
1501643,A0A8H9RDU4,gb|MTC66204.1|,69.159,321,97,1,5,323,9,329,4.070000e-167,478.0,98

In [11]:
blast_6 = pd.read_csv("uniprot_blast_results/uniprot_blast_query_6.log", sep='\t', header=None)
blast_6.columns = ["id", "subject_id", "identity_percentage", "alignment_length", "mismatches", "gap_opens", "query_start", "query_end", "subject_start", "subject_end", "expect_value", "bit_score", "query_coverage"]
blast_6

,id,subject_id,identity_percentage,alignment_length,mismatches,gap_opens,query_start,query_end,subject_start,subject_end,expect_value,bit_score,query_coverage
0,A0A8H9RDU8,ref|WP_158198217.1|,100.000,273,0,0,1,273,1,273,0.0,551.0,100
1,A0A8H9RDU8,ref|WP_139390202.1|,99.634,273,1,0,1,273,1,273,0.0,548.0,100
2,A0A8H9RDU8,ref|WP_219314135.1|,99.267,273,2,0,1,273,1,273,0.0,547.0,100
3,A0A8H9RDU8,ref|WP_039214790.1|,99.267,273,2,0,1,273,1,273,0.0,547.0,100
4,A0A8H9RDU8,gb|EIS3745776.1|,98.901,273,3,0,1,273,1,273,0.0,547.0,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1435298,T0PES4,ref|WP_103260951.1|,92.998,457,32,0,1,457,1,457,0.0,858.0,98
1435299,T0PES4,ref|WP_139494639.1|,91.453,468,38,1,1,468,1,466,0.0,858.0,100
1435300,T0PES4,ref|WP_268435419.1|,93.217,457,31,0,1,457,1,457,0.0,858.0,98
1435301,T0PES4,ref|WP_236281208.1|,91.667,468,37,1,1,468,1,466,0.0,858.0,100
1435302,T0PES4,ref|WP_262000039.1|,92.375,459,35,0,1,459,1,459,0.0,858.0,98

In [13]:
#Combining the all of the dataframe into one

# Create a list of your dataframes
dataframes = [blast_1, blast_2, blast_3, blast_4, blast_5, blast_6]

# Use pandas concat() function to combine them
blast_df = pd.concat(dataframes, ignore_index=True)
blast_df

,id,subject_id,identity_percentage,alignment_length,mismatches,gap_opens,query_start,query_end,subject_start,subject_end,expect_value,bit_score,query_coverage
0,A0A068FVC1,ref|WP_096106374.1|,100.000,179,0,0,1,179,1,179,2.120000e-130,373.0,100
1,A0A068FVC1,ref|WP_268029297.1|,99.441,179,1,0,1,179,1,179,4.280000e-130,372.0,100
2,A0A068FVC1,gb|AXL04880.1|,99.441,179,1,0,1,179,1,179,9.850000e-130,371.0,100
3,A0A068FVC1,ref|WP_101613939.1|,99.441,179,1,0,1,179,1,179,1.560000e-129,371.0,100
4,A0A068FVC1,ref|WP_279451246.1|,97.765,179,4,0,1,179,1,179,4.460000e-126,362.0,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8941891,T0PES4,ref|WP_103260951.1|,92.998,457,32,0,1,457,1,457,0.000000e+00,858.0,98
8941892,T0PES4,ref|WP_139494639.1|,91.453,468,38,1,1,468,1,466,0.000000e+00,858.0,100
8941893,T0PES4,ref|WP_268435419.1|,93.217,457,31,0,1,457,1,457,0.000000e+00,858.0,98
8941894,T0PES4,ref|WP_236281208.1|,91.667,468,37,1,1,468,1,466,0.000000e+00,858.0,100
8941895,T0PES4,ref|WP_262000039.1|,92.375,459,35,0,1,459,1,459,0.000000e+00,858.0,98

In [15]:
#save the dataframe as a csv file

blast_df.to_csv("blast_df_original.csv", index=False)

In [2]:
blast_df = pd.read_csv("/Users/zaidur/Documents/Sequence_Project/aeromonasBact/blast_df_original.csv")
blast_df

,id,subject_id,identity_percentage,alignment_length,mismatches,gap_opens,query_start,query_end,subject_start,subject_end,expect_value,bit_score,query_coverage
0,A0A068FVC1,ref|WP_096106374.1|,100.000,179,0,0,1,179,1,179,2.120000e-130,373.0,100
1,A0A068FVC1,ref|WP_268029297.1|,99.441,179,1,0,1,179,1,179,4.280000e-130,372.0,100
2,A0A068FVC1,gb|AXL04880.1|,99.441,179,1,0,1,179,1,179,9.850000e-130,371.0,100
3,A0A068FVC1,ref|WP_101613939.1|,99.441,179,1,0,1,179,1,179,1.560000e-129,371.0,100
4,A0A068FVC1,ref|WP_279451246.1|,97.765,179,4,0,1,179,1,179,4.460000e-126,362.0,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8941891,T0PES4,ref|WP_103260951.1|,92.998,457,32,0,1,457,1,457,0.000000e+00,858.0,98
8941892,T0PES4,ref|WP_139494639.1|,91.453,468,38,1,1,468,1,466,0.000000e+00,858.0,100
8941893,T0PES4,ref|WP_268435419.1|,93.217,457,31,0,1,457,1,457,0.000000e+00,858.0,98
8941894,T0PES4,ref|WP_236281208.1|,91.667,468,37,1,1,468,1,466,0.000000e+00,858.0,100
8941895,T0PES4,ref|WP_262000039.1|,92.375,459,35,0,1,459,1,459,0.000000e+00,858.0,98

In [6]:
#First, filtering the results by the query coverage

filtered_blast_df = blast_df[blast_df['query_coverage'] >= 100]
filtered_blast_df

,id,subject_id,identity_percentage,alignment_length,mismatches,gap_opens,query_start,query_end,subject_start,subject_end,expect_value,bit_score,query_coverage
0,A0A068FVC1,ref|WP_096106374.1|,100.000,179,0,0,1,179,1,179,2.120000e-130,373.0,100
1,A0A068FVC1,ref|WP_268029297.1|,99.441,179,1,0,1,179,1,179,4.280000e-130,372.0,100
2,A0A068FVC1,gb|AXL04880.1|,99.441,179,1,0,1,179,1,179,9.850000e-130,371.0,100
3,A0A068FVC1,ref|WP_101613939.1|,99.441,179,1,0,1,179,1,179,1.560000e-129,371.0,100
4,A0A068FVC1,ref|WP_279451246.1|,97.765,179,4,0,1,179,1,179,4.460000e-126,362.0,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8941888,T0PES4,ref|WP_108572109.1|,91.239,468,39,1,1,468,1,466,0.000000e+00,858.0,100
8941889,T0PES4,ref|WP_042012375.1|,91.667,468,37,1,1,468,1,466,0.000000e+00,858.0,100
8941890,T0PES4,ref|WP_211048767.1|,91.026,468,42,0,1,468,1,468,0.000000e+00,858.0,100
8941892,T0PES4,ref|WP_139494639.1|,91.453,468,38,1,1,468,1,466,0.000000e+00,858.0,100
8941894,T0PES4,ref|WP_236281208.1|,91.667,468,37,1,1,468,1,466,0.000000e+00,858.0,100

In [ ]:
"""
This is an alternate way to filter. The code is commented out


Firstly, filtering the results by the query coverage.
There is a new method applied here. Initially we wanted to filter sequences with 'query_coverage'=100
But some sequence may not have any hits with that amount of query_coverage. So to prevent removing any sequence
with lower 'query_coverage',we are filtering them by max 'query_coverage'. For example, for any sequence, if it
has hits with max 'query_coverage' of 100, we will filter with 100 'query_coverage'. But if it has hits only with
max 'query_coverage' of 90, we will filter with 'query_coverage'=90.
"""

# def filter_by_max_query_coverage(group):
#     max_query_coverage = group['query_coverage'].max()
#     return group[group['query_coverage'] == max_query_coverage]

# maxFiltered_blast_df = blast_df.groupby('id').apply(filter_by_max_query_coverage).reset_index(drop=True)
# maxFiltered_blast_df

In [7]:
#And then, filtering by the identity_percentage

filtered_blast_df = filtered_blast_df[filtered_blast_df['identity_percentage'] >= 80]
filtered_blast_df

,id,subject_id,identity_percentage,alignment_length,mismatches,gap_opens,query_start,query_end,subject_start,subject_end,expect_value,bit_score,query_coverage
0,A0A068FVC1,ref|WP_096106374.1|,100.000,179,0,0,1,179,1,179,2.120000e-130,373.0,100
1,A0A068FVC1,ref|WP_268029297.1|,99.441,179,1,0,1,179,1,179,4.280000e-130,372.0,100
2,A0A068FVC1,gb|AXL04880.1|,99.441,179,1,0,1,179,1,179,9.850000e-130,371.0,100
3,A0A068FVC1,ref|WP_101613939.1|,99.441,179,1,0,1,179,1,179,1.560000e-129,371.0,100
4,A0A068FVC1,ref|WP_279451246.1|,97.765,179,4,0,1,179,1,179,4.460000e-126,362.0,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8941888,T0PES4,ref|WP_108572109.1|,91.239,468,39,1,1,468,1,466,0.000000e+00,858.0,100
8941889,T0PES4,ref|WP_042012375.1|,91.667,468,37,1,1,468,1,466,0.000000e+00,858.0,100
8941890,T0PES4,ref|WP_211048767.1|,91.026,468,42,0,1,468,1,468,0.000000e+00,858.0,100
8941892,T0PES4,ref|WP_139494639.1|,91.453,468,38,1,1,468,1,466,0.000000e+00,858.0,100
8941894,T0PES4,ref|WP_236281208.1|,91.667,468,37,1,1,468,1,466,0.000000e+00,858.0,100

In [ ]:
"""
Alternate way to filter. The code is commented out

Secondly, filtering the results by the identity percentage.
There is a new method applied here. Initially we wanted to filter sequences with 'identity_percentage'>=80
But some sequence may not have any hits with that amount of identity_percentage. So to prevent removing any
sequence with lower identity_percentage ,we are filtering them by max 'identity_percentage'. If any sequence have
hits with max 'identity_percentage' lower than 80, we will filter it's hits with the max 'identity_percentage'.
But if it has hits with max 'identity_percentage' higher that 80, we will filter those with perecentage >= 80
For example, for any sequence, if it has hits with max 'identity_percentage' of 95, we will filter with 
'identity_percentage'>=80. But if it has hits only with max 'identity_percentage' of 75, we will filter
with 'identity_percentage'==75.
"""

# def filter_by_max_query_coverage(group):
#     max_query_coverage = group['identity_percentage'].max()
#     if max_query_coverage<80:
#         return group[group['identity_percentage'] == max_query_coverage]
#     else:
#         return group[group['identity_percentage'] >= 80]

# maxFiltered_blast_df = maxFiltered_blast_df.groupby('id').apply(filter_by_max_query_coverage).reset_index(drop=True)
# maxFiltered_blast_df

In [11]:
#All the hits of this sequence has lower query coverage

blast_df[blast_df['id'] == "Q9PRY2"]

,id,subject_id,identity_percentage,alignment_length,mismatches,gap_opens,query_start,query_end,subject_start,subject_end,expect_value,bit_score,query_coverage
8249490,Q9PRY2,sp|Q9PRY2.2|,100.0,16,0,0,2,17,2,17,0.084,36.2,94
8249491,Q9PRY2,gb|AAB30801.1|,100.0,16,0,0,2,17,1,16,0.085,36.2,94

In [8]:
#Cobmining the results to create blast features.

grouped = filtered_blast_df.groupby('id')

summary_blast_df = pd.DataFrame()
summary_blast_df['id'] = grouped['id'].first() # This will get the unique ids
summary_blast_df['count_blast'] = grouped.size() # This will count the number of rows for each id
summary_blast_df['AvgIdBlast'] = grouped['identity_percentage'].mean() # This will calculate the mean of 'identity_percentage' for each id

summary_blast_df = summary_blast_df.reset_index(drop=True) # Reset index
summary_blast_df

               id  count_blast  AvgIdBlast
0      A0A068FVC1            9   96.461556
1      A0A068FZD0           12   84.911333
2      A0A068FZK6           54   90.803259
3      A0A075P9Z7          291   96.272323
4      A0A075PBX8          297   97.017865
...           ...          ...         ...
29774      V5TDW0           19   89.891474
29775      V5YM41          299   95.769060
29776      W5JXD7          143   96.887196
29777      X5C4A1           22   88.887591
29778      X5C4A6           52   90.709077

[29779 rows x 3 columns]

In [59]:
blast_df

,id,subject_id,identity_percentage,alignment_length,mismatches,gap_opens,query_start,query_end,subject_start,subject_end,expect_value,bit_score,query_coverage
0,A0A068FVC1,ref|WP_096106374.1|,100.000,179,0,0,1,179,1,179,2.120000e-130,373.0,100
1,A0A068FVC1,ref|WP_268029297.1|,99.441,179,1,0,1,179,1,179,4.280000e-130,372.0,100
2,A0A068FVC1,gb|AXL04880.1|,99.441,179,1,0,1,179,1,179,9.850000e-130,371.0,100
3,A0A068FVC1,ref|WP_101613939.1|,99.441,179,1,0,1,179,1,179,1.560000e-129,371.0,100
4,A0A068FVC1,ref|WP_279451246.1|,97.765,179,4,0,1,179,1,179,4.460000e-126,362.0,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8941891,T0PES4,ref|WP_103260951.1|,92.998,457,32,0,1,457,1,457,0.000000e+00,858.0,98
8941892,T0PES4,ref|WP_139494639.1|,91.453,468,38,1,1,468,1,466,0.000000e+00,858.0,100
8941893,T0PES4,ref|WP_268435419.1|,93.217,457,31,0,1,457,1,457,0.000000e+00,858.0,98
8941894,T0PES4,ref|WP_236281208.1|,91.667,468,37,1,1,468,1,466,0.000000e+00,858.0,100
8941895,T0PES4,ref|WP_262000039.1|,92.375,459,35,0,1,459,1,459,0.000000e+00,858.0,98

In [15]:
summary_blast_df

               id  count_blast  AvgIdBlast
0      A0A068FVC1            9   96.461556
1      A0A068FZD0           12   84.911333
2      A0A068FZK6           54   90.803259
3      A0A075P9Z7          291   96.272323
4      A0A075PBX8          297   97.017865
...           ...          ...         ...
29774      V5TDW0           19   89.891474
29775      V5YM41          299   95.769060
29776      W5JXD7          143   96.887196
29777      X5C4A1           22   88.887591
29778      X5C4A6           52   90.709077

[29779 rows x 3 columns]

In [25]:
#Remove the sequences to match up with the latest uniprot_df.
#These are removed because they had unknow amino acids as X

# Define the list of ids to remove
ids_to_remove = ['A0A1Q8F8M2', 'A0A428VHZ9', 'P81903', 'Q03321']

# Remove the rows with specified ids
filtered_summary_df = summary_blast_df[~summary_blast_df['id'].isin(ids_to_remove)]

# Print the filtered DataFrame
filtered_summary_df

               id  count_blast  AvgIdBlast
0      A0A068FVC1            9   96.461556
1      A0A068FZD0           12   84.911333
2      A0A068FZK6           54   90.803259
3      A0A075P9Z7          291   96.272323
4      A0A075PBX8          297   97.017865
...           ...          ...         ...
29774      V5TDW0           19   89.891474
29775      V5YM41          299   95.769060
29776      W5JXD7          143   96.887196
29777      X5C4A1           22   88.887591
29778      X5C4A6           52   90.709077

[29775 rows x 3 columns]

In [28]:
#Save the dataframe into csv file

filtered_summary_df.to_csv("blast_feature_df.csv", index=False)